import type { AcquisitionCalendarResponse } from "@omnifin/contracts/calendar";

export const demoCalendarGeneratedAt = "2026-07-27T18:00:00.000Z";
export const demoCalendarStartAt = "2026-07-27T04:00:00.000Z";
export const demoCalendarEndAt = "2026-08-03T04:00:00.000Z";

const radarrSource = {
  displayName: "Radarr · Cinema",
  eventCount: 4,
  failure: null,
  id: "calendar_source_ABCDEFGHIJKLMNOPQRSTUV",
  service: "radarr",
  status: "healthy",
} as const;

const sonarrSource = {
  displayName: "Sonarr · Television",
  eventCount: 4,
  failure: null,
  id: "calendar_source_ZYXWVUTSRQPONMLKJIHGFE",
  service: "sonarr",
  status: "healthy",
} as const;

export const demoAcquisitionCalendar: AcquisitionCalendarResponse = {
  endAt: demoCalendarEndAt,
  events: [
    {
      availability: "monitored",
      endAt: null,
      episodeNumber: null,
      eventAt: "2026-07-27T18:30:00.000Z",
      id: "calendar_ABCDEFGHIJKLMNOPQRSTUV",
      kind: "movie",
      monitored: true,
      overview:
        "A cartographer follows a transmission beyond the last mapped corridor of human space.",
      releaseKind: "digital",
      runtimeMinutes: 128,
      seasonNumber: null,
      service: "radarr",
      sourceId: radarrSource.id,
      sourceName: radarrSource.displayName,
      subtitle: "Digital release",
      title: "The Far Meridian",
      year: 2026,
    },
    {
      availability: "available",
      endAt: "2026-07-28T02:46:00.000Z",
      episodeNumber: 6,
      eventAt: "2026-07-28T02:00:00.000Z",
      id: "calendar_BCDEFGHIJKLMNOPQRSTUVW",
      kind: "episode",
      monitored: true,
      overview: "The crew traces a signal that appears to anticipate every reply.",
      releaseKind: "episode",
      runtimeMinutes: 46,
      seasonNumber: 1,
      service: "sonarr",
      sourceId: sonarrSource.id,
      sourceName: sonarrSource.displayName,
      subtitle: "S01E06 · Echo Pattern",
      title: "Signal",
      year: 2026,
    },
    {
      availability: "missing",
      endAt: null,
      episodeNumber: null,
      eventAt: "2026-07-29T13:00:00.000Z",
      id: "calendar_CDEFGHIJKLMNOPQRSTUVWX",
      kind: "movie",
      monitored: true,
      overview: "Two rival pilots cross a planet whose horizon refracts memory itself.",
      releaseKind: "physical",
      runtimeMinutes: 114,
      seasonNumber: null,
      service: "radarr",
      sourceId: radarrSource.id,
      sourceName: radarrSource.displayName,
      subtitle: "Physical release",
      title: "Glass Horizon",
      year: 2025,
    },
    {
      availability: "queued",
      endAt: "2026-07-30T23:46:00.000Z",
      episodeNumber: 7,
      eventAt: "2026-07-30T23:00:00.000Z",
      id: "calendar_DEFGHIJKLMNOPQRSTUVWXY",
      kind: "episode",
      monitored: true,
      overview: "The receiver resolves a second voice hidden beneath the carrier wave.",
      releaseKind: "episode",
      runtimeMinutes: 46,
      seasonNumber: 1,
      service: "sonarr",
      sourceId: sonarrSource.id,
      sourceName: sonarrSource.displayName,
      subtitle: "S01E07 · Carrier",
      title: "Signal",
      year: 2026,
    },
    {
      availability: "monitored",
      endAt: null,
      episodeNumber: null,
      eventAt: "2026-07-31T16:00:00.000Z",
      id: "calendar_EFGHIJKLMNOPQRSTUVWXYZ",
      kind: "movie",
      monitored: true,
      overview: "A coastal town wakes to discover the tide has stopped beneath a copper sky.",
      releaseKind: "cinema",
      runtimeMinutes: 121,
      seasonNumber: null,
      service: "radarr",
      sourceId: radarrSource.id,
      sourceName: radarrSource.displayName,
      subtitle: "Cinema release",
      title: "Aster Bay",
      year: 2026,
    },
    {
      availability: "monitored",
      endAt: "2026-08-01T20:54:00.000Z",
      episodeNumber: 4,
      eventAt: "2026-08-01T20:00:00.000Z",
      id: "calendar_FGHIJKLMNOPQRSTUVWXYZa",
      kind: "episode",
      monitored: true,
      overview: "Mara enters the archive while the station completes its longest night.",
      releaseKind: "episode",
      runtimeMinutes: 54,
      seasonNumber: 2,
      service: "sonarr",
      sourceId: sonarrSource.id,
      sourceName: sonarrSource.displayName,
      subtitle: "S02E04 · Night Index",
      title: "Northern Lights",
      year: 2026,
    },
    {
      availability: "monitored",
      endAt: null,
      episodeNumber: null,
      eventAt: "2026-08-02T15:30:00.000Z",
      id: "calendar_GHIJKLMNOPQRSTUVWXYZab",
      kind: "movie",
      monitored: true,
      overview: "A quiet observatory receives one final image from a vanished expedition.",
      releaseKind: "digital",
      runtimeMinutes: 106,
      seasonNumber: null,
      service: "radarr",
      sourceId: radarrSource.id,
      sourceName: radarrSource.displayName,
      subtitle: "Digital release",
      title: "Last Light at Orison",
      year: 2026,
    },
    {
      availability: "monitored",
      endAt: "2026-08-02T23:42:00.000Z",
      episodeNumber: 3,
      eventAt: "2026-08-02T23:00:00.000Z",
      id: "calendar_HIJKLMNOPQRSTUVWXYZabc",
      kind: "episode",
      monitored: true,
      overview: "The station's oldest map reveals a route no one remembers drawing.",
      releaseKind: "episode",
      runtimeMinutes: 42,
      seasonNumber: 2,
      service: "sonarr",
      sourceId: sonarrSource.id,
      sourceName: sonarrSource.displayName,
      subtitle: "S02E03 · The Fold",
      title: "The Long Meridian",
      year: 2026,
    },
  ],
  failures: [],
  generatedAt: demoCalendarGeneratedAt,
  nextCursor: null,
  sourceTruncated: false,
  sources: [radarrSource, sonarrSource],
  startAt: demoCalendarStartAt,
  state: "complete",
  summary: { available: 1, episodes: 4, missing: 1, movies: 4, queued: 1, total: 8 },
};

export const emptyAcquisitionCalendar: AcquisitionCalendarResponse = {
  ...demoAcquisitionCalendar,
  events: [],
  sources: [
    { ...radarrSource, eventCount: 0 },
    { ...sonarrSource, eventCount: 0 },
  ],
  summary: { available: 0, episodes: 0, missing: 0, movies: 0, queued: 0, total: 0 },
};

export const unconfiguredAcquisitionCalendar: AcquisitionCalendarResponse = {
  ...emptyAcquisitionCalendar,
  sources: [],
  state: "unconfigured",
};

const sonarrFailure = {
  code: "timeout",
  message: "Sonarr did not respond before the deadline.",
  occurredAt: demoCalendarGeneratedAt,
  operation: "acquisition.calendar",
  retryable: true,
  service: "sonarr",
} as const;

const degradedEvents = demoAcquisitionCalendar.events.filter((event) => event.service === "radarr");

export const degradedAcquisitionCalendar: AcquisitionCalendarResponse = {
  ...demoAcquisitionCalendar,
  events: degradedEvents,
  failures: [sonarrFailure],
  sources: [
    radarrSource,
    {
      ...sonarrSource,
      eventCount: 0,
      failure: sonarrFailure,
      status: "unavailable",
    },
  ],
  state: "degraded",
  summary: { available: 0, episodes: 0, missing: 1, movies: 4, queued: 0, total: 4 },
};
