import type { DownloadQueueResponse } from "@omnifin/contracts/downloads";

export const demoDownloadQueueGeneratedAt = "2026-07-28T03:00:00.000Z";

export const demoDownloadQueue: DownloadQueueResponse = {
  clients: [
    {
      connectorId: "qbittorrent-main",
      displayName: "qBittorrent · Cinema",
      failure: null,
      itemCount: 2,
      rateBytesPerSecond: 48_600_000,
      service: "qbittorrent",
      status: "healthy",
    },
    {
      connectorId: "sabnzbd-main",
      displayName: "SABnzbd · Series",
      failure: null,
      itemCount: 1,
      rateBytesPerSecond: 12_800_000,
      service: "sabnzbd",
      status: "healthy",
    },
  ],
  failures: [],
  generatedAt: demoDownloadQueueGeneratedAt,
  items: [
    {
      addedAt: "2026-07-28T02:40:00.000Z",
      category: "movies-uhd",
      client: "qbittorrent",
      clientName: "qBittorrent · Cinema",
      connectorId: "qbittorrent-main",
      etaSeconds: 720,
      id: "download_ABCDEFGHIJKLMNOPQRSTUV",
      leechers: 4,
      progress: 0.72,
      protocol: "torrent",
      rateBytesPerSecond: 48_600_000,
      remainingBytes: 5_200_000_000,
      seeders: 38,
      sizeBytes: 18_420_000_000,
      state: "downloading",
      title: "The.Far.Meridian.2026.2160p.WEB-DL",
    },
    {
      addedAt: null,
      category: "series",
      client: "sabnzbd",
      clientName: "SABnzbd · Series",
      connectorId: "sabnzbd-main",
      etaSeconds: 240,
      id: "download_ZYXWVUTSRQPONMLKJIHGFE",
      leechers: null,
      progress: 0.91,
      protocol: "usenet",
      rateBytesPerSecond: 12_800_000,
      remainingBytes: 1_100_000_000,
      seeders: null,
      sizeBytes: 12_100_000_000,
      state: "downloading",
      title: "Signal.S01E07.1080p.WEB-DL",
    },
    {
      addedAt: "2026-07-28T01:48:00.000Z",
      category: "movies",
      client: "qbittorrent",
      clientName: "qBittorrent · Cinema",
      connectorId: "qbittorrent-main",
      etaSeconds: null,
      id: "download_0123456789abcdefghijkl",
      leechers: 0,
      progress: 0.44,
      protocol: "torrent",
      rateBytesPerSecond: 0,
      remainingBytes: 8_400_000_000,
      seeders: 0,
      sizeBytes: 15_000_000_000,
      state: "stalled",
      title: "Glass.Horizon.2025.1080p.BluRay",
    },
  ],
  state: "complete",
  summary: {
    attention: 1,
    downloading: 2,
    paused: 0,
    queued: 0,
    remainingBytes: 14_700_000_000,
    total: 3,
    totalRateBytesPerSecond: 61_400_000,
  },
  truncated: false,
};
