function frozenChecks(checks) {
  return Object.freeze(checks);
}

export const COMPATIBILITY_CHECKS = Object.freeze({
  authentik: frozenChecks([
    "authorization_code_pkce",
    "immutable_issuer_subject",
    "jit_pending_jellyfin_link",
    "privileged_group_role_mapping",
    "guarded_role_mapping_update",
    "provider_initiated_backchannel_logout",
    "rp_initiated_logout",
    "secret_leak_inspection",
  ]),
  bazarr: frozenChecks([
    "authentication",
    "credentialRejection",
    "emptyLibraryRead",
    "fixtureMediaProvisioning",
    "subtitleArtifact",
    "subtitleDownload",
    "subtitleSearch",
    "versionDiscovery",
  ]),
  jellyfin: frozenChecks([
    "direct_range",
    "hls_transcode",
    "identity_invalid_password",
    "identity_mismatched_quick_connect_secret",
    "identity_password",
    "identity_public_info",
    "identity_quick_connect",
    "library_catalog",
    "progress_persistence",
    "restart_reconnect",
    "track_audio",
    "track_subtitle",
  ]),
  oidc: frozenChecks([
    "authorization_code_pkce",
    "state_nonce_validation",
    "strict_issuer_and_standard_claims",
    "immutable_issuer_subject",
    "jit_viewer_pending_jellyfin_link",
    "explicit_group_role_mapping",
    "guarded_role_mapping_update",
    "optional_logout_capability_negotiation",
    "local_logout_fallback",
    "secret_leak_inspection",
  ]),
  prowlarr: frozenChecks([
    "applicationRead",
    "authentication",
    "credentialRejection",
    "failureRead",
    "fixtureIndexerProvisioning",
    "indexerRead",
    "indexerSafeTest",
    "systemHealthRead",
    "versionDiscovery",
  ]),
  qbittorrent: frozenChecks([
    "authentication",
    "coordinatedPauseResume",
    "credentialRejection",
    "exactPause",
    "exactPromotion",
    "exactResume",
    "preserveFilesRemoval",
    "queueRead",
  ]),
  radarr: frozenChecks([
    "authentication",
    "calendarRead",
    "credentialRejection",
    "fixtureTitleProvisioning",
    "monitoringRead",
    "monitoringRestore",
    "monitoringUpdate",
    "queueMutationGuard",
    "queueRead",
    "storageRead",
    "systemHealthRead",
    "versionDiscovery",
  ]),
  sabnzbd: frozenChecks([
    "authentication",
    "coordinatedPauseResume",
    "credentialRejection",
    "exactPause",
    "exactPromotion",
    "exactResume",
    "preserveFilesRemoval",
    "queueRead",
  ]),
  seerr: frozenChecks([
    "authentication",
    "credentialRejection",
    "delegatedIdentity",
    "duplicateRejection",
    "multiWordSearch",
    "pendingRequestCreation",
    "requestDecline",
    "requestReview",
    "versionDiscovery",
  ]),
  sonarr: frozenChecks([
    "authentication",
    "calendarRead",
    "credentialRejection",
    "fixtureTitleProvisioning",
    "monitoringRead",
    "monitoringRestore",
    "monitoringUpdate",
    "queueMutationGuard",
    "queueRead",
    "storageRead",
    "systemHealthRead",
    "versionDiscovery",
  ]),
});
